### ISSUE TITLE
Convert raw raman dx data to npy and hdf dataframe

### ISSUE THREAD

**Issue by WentongZhou** [ALebrun-108/BoxSERS#3]
Hi there,

Thanks for this fantastic job. In your package, you use hdf and npy dataframe to store raman data. Could you provide some information on how you convert those raw Raman data (for example dx format data) to those h5 and npy data?

Thanks,
Wentong

**Comment by ALebrun-108** [comment]
Hi,

First of all, I'm very glad to hear that you like my work and it motivates me to keep on improving it! Now, in response to your question, I usually convert and compile my raw spectra into pandas dataframe, which can then be saved as a numpy array or an hdf5 database.  This approach has proven to be an effective way to structure my raw spectra before saving them, and allows me to use various data visualization functions related to pandas.  So I think it would be possible to convert your data (dx format data, csv, ...)  to pandas dataframe using the pd.read_csv function.

I hope I have answered your question correctly, and I remain available to offer more details if necessary.

Have a nice day,  

Alexis Lebrun

**Comment by WentongZhou** [comment]
Hi,
Thanks for the help! we will cite your work when we publish our results in the near future.


Best,
Wentong

**Comment by renjith-vs** [comment]
@ALebrun-108 Hi Alexis Lebrun, your contribution to those who work in spectrum analysis is great. as @WentongZhou said, it would be great if you provide how to convert the raw spectral data along with metadata (demographic details) such as (name, age, and molecule 1, molecule 2 ...) into data frame .h5. 

Anticipating your positive responses.
with regards,
Renjith

**Comment by ALebrun-108** [comment]
Hi ,

Glad to hear you like it too. To answer your question, it is difficult to provide a single code that allows, regardless of the format, to convert the raw spectra into the same format for the application of this code. Please note that the hdf5 format is used here only to allow users of the code to use the spectra we have received in the lab, and is optional for using this package with your own spectra. In fact, to use this package, you just need to generate numpy arrays from your code (one array for the spectra and another one for the labels). 

I also provided above a draft of the code we used to convert our raw spectra ( a custom .txt file with metadata) into dataframe pandas, which can be saved as .hdf5 files and from which you can extract numpy arrays easily. I do note, however, that it might be interesting to provide codes to use the main basic spectra formats used (.spe, .Grams, .spc, etc.), and I plan to add this in the next update.  

Hopefully this will be useful to you,

Alexis Lebrun

**Comment by renjith-vs** [comment]
@ALebrun-108 Thanks for writing me back. For a better understanding, can you show the data format of raw spectral time series data in a .txt file before converting it into data frame. This may even help to analyze how the data is represented against the wave number. Again how do you correlate the spectral intensity against the wavenumber (RamanShift) since the bile acids data frame and Raman shift are taken separately.

Anticipating your positive responses.

**Comment by ALebrun-108** [comment]
Sorry for the delay, 

To answer your questions, the spectra used in this software are not time series, but rather vibrational spectra, which are measured with a spectrometer calibrated in wavelengths (wavelengths can be converted to Raman shift and are both units used in spectroscopy). Thus, the spectra and the Raman shift are not measured separately, but at the same time. 

To simplify the use of the package, you can ignore the Raman shift values as they have no real impact on the operation of the algorithms and are mainly used to associate the Raman spectral bands with specific vibrational groups

To answer your request, I attach below an image of the data format with annotations added afterwards :

![github_answer](https://user-images.githubusercontent.com/59709058/204885856-0c187eb9-60f3-413e-ae71-00f4716910bc.png)


Hopefully this will be useful to you,

Alexis Lebrun
